# Generated by Django 5.0.3 on 2025-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False, help_text='Задача просрочена'),
        ),
    ]
